kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "mlbparks.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  mongodbUser: {{ randAlphaNum 5 | b64enc }}
  mongodbPassword: {{ randAlphaNum 12 | b64enc }}
  mongodbDatabase: cm9vdA==
  mongodbAdminPassword: {{ randAlphaNum 12 | b64enc }}
