apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: {{ template "mlbparks.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
    protocol: TCP
  selector:
    deployment: {{ .Release.Name }}-mongodb
